---
title: "t_tests"
output: html_document
---
```{r}
library(readr)
library(dplyr)

reviewlocation <- read_csv('final_data.csv')
```
Function that runs t-tests for different CBSA (Core Based Statistical Areas) by ownership type (public or private ownership) and cost (paid or free). 
```{r}


t_test_CBSA <- function(x){
  publicprivate1 <- reviewlocation %>%
  select(`Location Id`, Name, bestPOIGroup, `Predicted Sentiment`, CBSA, Cost, publicPrivate) %>%
  filter(!is.na(publicPrivate)) %>%
  filter(bestPOIGroup != 'Other') %>%
  filter(bestPOIGroup != 'Unknown') %>%
  filter(CBSA == x) %>%
  mutate(count=n())
  
#dataframe of all publicly owned and free stations in the CBSA
publicfree <- publicprivate1 %>%
  filter(publicPrivate == 'Public') %>%
  filter(Cost == 'Free') %>%
  filter(`Predicted Sentiment` == 'POSITIVE' | `Predicted Sentiment` == 'NEGATIVE') %>%
  mutate(sentiment_values = ifelse(`Predicted Sentiment` == 'POSITIVE', 1, 0)) %>%
  group_by(`Location Id`) %>%
  mutate(prop = 1-sum(sentiment_values)/n()) %>%
  distinct(prop, `Location Id`)

#dataframe of all privately owned and free stations in the CBSA
privatefree <- publicprivate1 %>%
  filter(publicPrivate == 'Private') %>%
  filter(Cost == 'Free') %>%
  filter(`Predicted Sentiment` == 'POSITIVE' | `Predicted Sentiment` == 'NEGATIVE') %>%
  mutate(sentiment_values = ifelse(`Predicted Sentiment` == 'POSITIVE', 1, 0)) %>%
  group_by(`Location Id`) %>%
  mutate(prop = 1-sum(sentiment_values)/n()) %>%
  distinct(prop, `Location Id`)

#dataframe of all privately owned and paid stations in the CBSA
privatepaid <- publicprivate1 %>%
  filter(publicPrivate == 'Private') %>%
  filter(Cost == 'Paid') %>%
  filter(`Predicted Sentiment` == 'POSITIVE' | `Predicted Sentiment` == 'NEGATIVE') %>%
  mutate(sentiment_values = ifelse(`Predicted Sentiment` == 'POSITIVE', 1, 0)) %>%
  group_by(`Location Id`) %>%
  mutate(prop = 1-sum(sentiment_values)/n()) %>%
  distinct(prop, `Location Id`)

#dataframe of all publicly owned and paid stations in the CBSA
publicpaid <- publicprivate1 %>%
  filter(publicPrivate == 'Public') %>%
  filter(Cost == 'Paid') %>%
  filter(`Predicted Sentiment` == 'POSITIVE' | `Predicted Sentiment` == 'NEGATIVE') %>%
  mutate(sentiment_values = ifelse(`Predicted Sentiment` == 'POSITIVE', 1, 0)) %>%
  group_by(`Location Id`) %>%
  mutate(prop = 1-sum(sentiment_values)/n()) %>%
  distinct(prop, `Location Id`)

#runs t-test for public free v. paid
publicfreepaid <- t.test(publicfree$prop, publicpaid$prop, var.equal = FALSE)

#runs t-test for private free v. paid
privatefreepaid <- t.test(privatefree$prop, privatepaid$prop, var.equal = FALSE)

#for each CBSA, it returns a list of the CBSA, alongside the output for each t-test
results_cbsa <- list(x, publicfreepaid, privatefreepaid, publicprivate1$count[1])

#returns list
return(results_cbsa)
}
```

```{r}
#this is the list of the top 2 markets by number of reviews in each of the 9 census subdivisions in the US, reversed so that the list is in size order
cbsa <- rev(list(
'Chattanooga, TN-GA',
'Kansas City, MO-KS',
'Hartford-West Hartford-East Hartford, CT',
'Austin-Round Rock, TX',
'Minneapolis-St. Paul-Bloomington, MN-WI',
'Detroit-Warren-Dearborn, MI',
'Denver-Aurora-Lakewood, CO',
'Nashville-Davidson--Murfreesboro--Franklin, TN',
'Dallas-Fort Worth-Arlington, TX',
'Boston-Cambridge-Newton, MA-NH',
'Philadelphia-Camden-Wilmington, PA-NJ-DE-MD',
'Chicago-Naperville-Elgin, IL-IN-WI',
'New York-Newark-Jersey City, NY-NJ-PA',
'Phoenix-Mesa-Scottsdale, AZ',
'Washington-Arlington-Alexandria, DC-VA-MD-WV',
'Atlanta-Sandy Springs-Roswell, GA',
'San Francisco-Oakland-Hayward, CA',
'Los Angeles-Long Beach-Anaheim, CA'))

#for each CBSA, run the set of t-tests
cbsa_tests <- lapply(cbsa, FUN = t_test_CBSA)

#writes outputs
cbsa_tests_output <- capture.output(print(cbsa_tests))

#writes all outputs into a file
writeLines(cbsa_tests_output, con = file("cbsa_ttest.txt"))
```
Function that runs t-tests for different states by ownership type (public or private ownership) and cost (paid or free). 
```{r}
#filters on the given state 
t_test_state <- function(y){
  publicprivate1 <- reviewlocation %>%
  select(`Location Id`, Name, bestPOIGroup, `Predicted Sentiment`, CBSA, Cost, publicPrivate, stateAb) %>%
  filter(!is.na(publicPrivate)) %>%
  filter(bestPOIGroup != 'Other') %>%
  filter(bestPOIGroup != 'Unknown') %>%
  filter(stateAb == y) %>%
  mutate(count=n())


#dataframe of all publicly owned and free stations in the state
publicfree <- publicprivate1 %>%
  filter(publicPrivate == 'Public') %>%
  filter(Cost == 'Free') %>%
  filter(`Predicted Sentiment` == 'POSITIVE' | `Predicted Sentiment` == 'NEGATIVE') %>%
  mutate(sentiment_values = ifelse(`Predicted Sentiment` == 'POSITIVE', 1, 0)) %>%
  group_by(`Location Id`) %>%
  mutate(prop = 1-sum(sentiment_values)/n()) %>%
  distinct(prop, `Location Id`)

#dataframe of all privately owned and free stations in the state
privatefree <- publicprivate1 %>%
  filter(publicPrivate == 'Private') %>%
  filter(Cost == 'Free') %>%
  filter(`Predicted Sentiment` == 'POSITIVE' | `Predicted Sentiment` == 'NEGATIVE') %>%
  mutate(sentiment_values = ifelse(`Predicted Sentiment` == 'POSITIVE', 1, 0)) %>%
  group_by(`Location Id`) %>%
  mutate(prop = 1-sum(sentiment_values)/n()) %>%
  distinct(prop, `Location Id`)

#dataframe of all privately owned and paid stations in the state
privatepaid <- publicprivate1 %>%
  filter(publicPrivate == 'Private') %>%
  filter(Cost == 'Paid') %>%
  filter(`Predicted Sentiment` == 'POSITIVE' | `Predicted Sentiment` == 'NEGATIVE') %>%
  mutate(sentiment_values = ifelse(`Predicted Sentiment` == 'POSITIVE', 1, 0)) %>%
  group_by(`Location Id`) %>%
  mutate(prop = 1-sum(sentiment_values)/n()) %>%
  distinct(prop, `Location Id`)

#dataframe of all publicly owned and paid stations in the CBSA
publicpaid <- publicprivate1 %>%
  filter(publicPrivate == 'Public') %>%
  filter(Cost == 'Paid') %>%
  filter(`Predicted Sentiment` == 'POSITIVE' | `Predicted Sentiment` == 'NEGATIVE') %>%
  mutate(sentiment_values = ifelse(`Predicted Sentiment` == 'POSITIVE', 1, 0)) %>%
  group_by(`Location Id`) %>%
  mutate(prop = 1-sum(sentiment_values)/n()) %>%
  distinct(prop, `Location Id`)

#runs t-test for public free v. paid
publicfreepaid <- t.test(publicfree$prop, publicpaid$prop, var.equal = FALSE)

#runs t-test for private free v. paid
privatefreepaid <- t.test(privatefree$prop, privatepaid$prop, var.equal = FALSE)

#for each CBSA, it returns a list of the CBSA, alongside the output for each t-test
results_states <- list(y, publicfreepaid, privatefreepaid, publicprivate1$count[1])

#returns list
return(results_states)
}
```

```{r}
#this is the list of the top 20 state markets by number of reviews
state <- list('CA',
'WA',
'OR',
'GA',
'FL',
'MD',
'AZ',
'NY',
'TX',
'VA',
'PA',
'NC',
'CO',
'IL',
'MA',
'TN',
'MI',
'OH',
'NJ',
'HI')

#for each state, run the set of t-tests
state_tests <- lapply(state, FUN = t_test_state)

#writes outputs
state_tests_output <- capture.output(print(state_tests))

#writes all outputs into a file
writeLines(state_tests_output, con = file("state_ttest.txt"))
```
#recreates state table
```{python}
fileName = "state_ttest.txt"
with open(fileName) as f:
   lines = f.readlines()

lines = [line.rstrip('\n').strip() for line in lines]

stateNames = {
   'Alabama': 'AL',
   'Alaska': 'AK',
   'Arizona': 'AZ',
   'Arkansas': 'AR',
   'California': 'CA',
   'Colorado': 'CO',
   'Connecticut': 'CT',
   'Delaware': 'DE',
   'Florida': 'FL',
   'Georgia': 'GA',
   'Hawaii': 'HI',
   'Idaho': 'ID',
   'Illinois': 'IL',
   'Indiana': 'IN',
   'Iowa': 'IA',
   'Kansas': 'KS',
   'Kentucky': 'KY',
   'Louisiana': 'LA',
   'Maine': 'ME',
   'Maryland': 'MD',
   'Massachusetts': 'MA',
   'Michigan': 'MI',
   'Minnesota': 'MN',
   'Mississippi': 'MS',
   'Missouri': 'MO',
   'Montana': 'MT',
   'Nebraska': 'NE',
   'Nevada': 'NV',
   'New Hampshire': 'NH',
   'New Jersey': 'NJ',
   'New Mexico': 'NM',
   'New York': 'NY',
   'North Carolina': 'NC',
   'North Dakota': 'ND',
   'Ohio': 'OH',
   'Oklahoma': 'OK',
   'Oregon': 'OR',
   'Pennsylvania': 'PA',
   'Rhode Island': 'RI',
   'South Carolina': 'SC',
   'South Dakota': 'SD',
   'Tennessee': 'TN',
   'Texas': 'TX',
   'Utah': 'UT',
   'Vermont': 'VT',
   'West Virginia': 'WV',
   'Virginia': 'VA',
   'Washington': 'WA',
   'Wisconsin': 'WI',
   'Wyoming': 'WY',
   "District of Columbia": "DC",
}

#Flips the dictionary (keys become values, values become keys)
stateNames = {val:key for key,val in stateNames.items()}

numStates = 20
for i in range(numStates):
   toPrint = list()
   spacer = 36
   
   NameIndex = int(i * spacer + 2)
   stateAbbrev = lines[NameIndex].split()[1][1:3]
   toPrint.append(stateAbbrev)
   
   pValPubIndex = i * spacer + 9
   pValPub = lines[pValPubIndex].split()[-1]
   
   
   meanPubIndex = i * spacer + 15
   xPubMean, yPubMean = lines[meanPubIndex].split()
   toPrint.append(xPubMean)
   toPrint.append(yPubMean)
   toPrint.append(pValPub)
   
   pValPrivIndex = i * spacer + 23
   pValPriv = lines[pValPrivIndex].split()[-1]

   meanPrivIndex = i * spacer + 29
   xPrivMean, yPrivMean = lines[meanPrivIndex].split()
   toPrint.append(xPrivMean)
   toPrint.append(yPrivMean)
   toPrint.append(pValPriv)
   
   countIndex = i * spacer + 33
   count = lines[countIndex].split()[1]
   toPrint.append(count)
   
   
   
   
   openString = "{0:.2f} & {1:.2f} & {2:.2f} & {3:.2f} & {4:.2f} & {5:.2f} & "
   openString = openString.format(float(toPrint[1]), float(toPrint[2]), float(toPrint[3]),
                           float(toPrint[4]), float(toPrint[5]), float(toPrint[6]))
   
   
   latexLine = stateNames[stateAbbrev] + " & " + openString + count + r" \\"
   print(latexLine)
```
#recreates the cbsa table
```{python}
fileName = "cbsa_ttest.txt"
with open(fileName) as f:
   lines = f.readlines()

lines = [line.rstrip('\n').strip() for line in lines]

cbsaNames = {
'Los Angeles-Long Beach-Anaheim, CA': 'Los',
'San Francisco-Oakland-Hayward, CA': 'San',
'Atlanta-Sandy Springs-Roswell, GA': 'Atl',
'Washington-Arlington-Alexandria, DC-VA-MD-WV': 'Was',
'Phoenix-Mesa-Scottsdale, AZ': 'Pho',
'New York-Newark-Jersey City, NY-NJ-PA': 'New',
'Chicago-Naperville-Elgin, IL-IN-WI': 'Chi',
'Philadelphia-Camden-Wilmington, PA-NJ-DE-MD': 'Phi',
'Boston-Cambridge-Newton, MA-NH': 'Bos',
'Dallas-Fort Worth-Arlington, TX': 'Dal',
'Nashville-Davidson--Murfreesboro--Franklin, TN': 'Nas',
'Denver-Aurora-Lakewood, CO': 'Den',
'Detroit-Warren-Dearborn, MI': 'Det',
'Minneapolis-St. Paul-Bloomington, MN-WI': 'Min',
'Austin-Round Rock, TX': 'Aus',
'Hartford-West Hartford-East Hartford, CT': 'Har',
'Kansas City, MO-KS': 'Kan',
'Chattanooga, TN-GA': 'Cha',
}

#Flips the dictionary (keys become values, values become keys)
cbsaNames = {val:key for key,val in cbsaNames.items()}

numCBSA = 18
for i in range(numCBSA):
   toPrint = list()
   spacer = 36
   
   NameIndex = int(i * spacer + 2)
   cbsaAbbrev = lines[NameIndex].split()[1][1:4]
   toPrint.append(cbsaAbbrev)
   
   pValPubIndex = i * spacer + 9
   pValPub = lines[pValPubIndex].split()[-1]
   
   
   meanPubIndex = i * spacer + 15
   xPubMean, yPubMean = lines[meanPubIndex].split()
   toPrint.append(xPubMean)
   toPrint.append(yPubMean)
   toPrint.append(pValPub)
   
   pValPrivIndex = i * spacer + 23
   pValPriv = lines[pValPrivIndex].split()[-1]

   meanPrivIndex = i * spacer + 29
   xPrivMean, yPrivMean = lines[meanPrivIndex].split()
   toPrint.append(xPrivMean)
   toPrint.append(yPrivMean)
   toPrint.append(pValPriv)
   
   countIndex = i * spacer + 33
   count = lines[countIndex].split()[1]
   toPrint.append(count)
   
   
   
   
   openString = "{0:.2f} & {1:.2f} & {2:.2f} & {3:.2f} & {4:.2f} & {5:.2f} & "
   openString = openString.format(float(toPrint[1]), float(toPrint[2]), float(toPrint[3]),
                           float(toPrint[4]), float(toPrint[5]), float(toPrint[6]))
   
   
   latexLine = cbsaNames[cbsaAbbrev] + " & " + openString + count + r" \\"
   print(latexLine)
```

